name: grin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.0
  logger: ^2.5.0
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.3
  flutter_bloc: ^9.1.0
  hive_generator: ^2.0.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.1
  animate_do: ^4.2.0
  hive_flutter: ^1.1.0
  scale_button: ^2.1.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  dartz: ^0.10.1
  http: ^1.3.0
  path_provider: ^2.1.5
  http_parser: ^4.1.2
  video_player: ^2.9.5
  chewie: ^1.11.1
  build_runner: ^2.4.15
  path: ^1.9.1

dev_dependencies:
  freezed: ^2.5.2

  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/sf_pro/Montserrat-Black.ttf
        weight: 900
      - asset: assets/fonts/sf_pro/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/sf_pro/Montserrat-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/sf_pro/Montserrat-Thin.ttf
        weight: 200
      - asset: assets/fonts/sf_pro/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/sf_pro/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/sf_pro/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/sf_pro/Montserrat-Thin.ttf
        weight: 100